###

POST http://localhost:5885/caption
Content-Type: application/json

{
    "image_url": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQS2DKvqhyVtI8MMAC8j2oP-2-JRryjBkNGhA&usqp=CAU"
}

###

POST https://ti6.fornaxhost.net/caption
Content-Type: application/json

{
    "image_url": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQS2DKvqhyVtI8MMAC8j2oP-2-JRryjBkNGhA&usqp=CAU"
}

###
